server:
  port: 8080
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  datasource:
    url: jdbc:mariadb://localhost:3306/springboot_mariadb
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  flyway:
    table: flyway_schema_history
    sql-migration-prefix: V
    sql-migration-separator: _
    sql-migration-suffixes: .sql
    out-of-order: false
    validate-on-migrate: true
  cache:
    caffeine:
    #spec: 'initialCapacity=100,maximumSize=500,expireAfterAccess=5m,recordStats'
cron:
  expression:
      customer: '* 0/1 * * * ?'
management:
  endpoints:
    web:
      exposure:
        include: heapdump,flyway,loggers,prometheus,threaddump,info,metrics,health
