#spring.cache.cache-names=AIRCRAFTS,SECOND_CACHE
#spring.cache.caffeine.spec=maximumSize=500,refreshAfterWrite=600s,recordStats

# http://localhost:8080/h2-console
spring:
  h2:
    console:
      enabled=true:
  jpa:
    show-sql=true:
    properties:
      hibernate:
        format_sql:
        generate_statistics=true:logging:
  pattern.console: %d{HH:mm:ss} - %msg%n
  level.org.springframework: info
  logging:
    level:
      org:
        hibernate:
          type=trace:
          stat=debug:


